config/routes.rb
Stashed::Application.routes.draw do
 get "log_in" => "sessions#new", :as => "log_in"
 get "log_out" => "sessions#destroy", :as => "log_out"

 root :to => "services#index"
 resources :users
 resources :sessions
 resources :events
 resources :statuses
 resources :services

  get "home/index"

end

app/models/service.rb
class Service < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :events, :dependent => :destroy
  accepts_nested_attributes_for :events

  def get_all_statuses
    statuses.select("events.id, events.message, events.created_at, statuses.image").order("events.created_at DESC")
    
  end #, :allow_destroy => true
end


#class Question < ActiveRecord::Base
#  belongs_to :survey
#end
#class Survey < ActiveRecord::Base
#    has_many :questions, :dependent => :destroy
#    accepts_nested_attributes_for :questions
#end
#
#- form_for @survey do |f|
#  = f.error_messages
#  %p
#    = f.label :name
#    %br/
#    = f.text_field :name
#  - f.fields_for :questions do |builder|
#    %p
#      = builder.label :content, "Question"
#      %br/
#      = builder.text_area :content, :rows => 3
#  %p= f.submit "Submit"

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    @statuses = Status.all
    @event = Event.joins('INNER JOIN services ON events.service_id = services.id INNER JOIN statuses ON events.status_id = statuses.id').order("created_at DESC")
    @status = Status.joins('INNER JOIN events ON statuses.id = events.status_id INNER JOIN services ON events.service_id = services.id')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])
    @service.events.all
    @event = Event.joins('INNER JOIN services ON events.service_id = services.id').where("events.service_id= #{params[:id]}").order("created_at DESC")
    @status = Status.joins('INNER JOIN events ON statuses.id = events.status_id INNER JOIN services ON events.service_id = services.id').where("events.service_id= #{params[:id]}" )
    @statuses = Status.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new
    @service.events.build
    @statuses = Status.all
    @count = Event.where(:service_id  => params[:id]).count

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @count = Event.where(:service_id  => params[:id]).count
    @service = Service.find(params[:id])
    @event = @service.events.build
    @statuses = Status.all
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])
    #@events = @service.events.build

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end

    #respond_to do |format|
    #  format.html # new.html.erb
    #  format.json { render json: @event }
    #end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])
    #@event = @service.events.create(params[:id])
    #@company = Company.find_or_create_by_name(params[:company][:name])
    #@person  = @company.people.create(params[:person])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json

  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :ok }
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.haml
= simple_form_for(@service, :html => { :class => 'form-horizontal' }) do |f|
  -if @service.errors.any?
    #error_explanation
      %h2= "#{pluralize(@service.errors.count, "error")} prohibited this service from being saved:"
      %ul
        - @service.errors.full_messages.each do |msg|
          %li= msg
  = f.input :name, :wrapper => :prepend, :label => false do
    = content_tag :span, "Name", :class => "add-on"
    = f.input_field :name
  = f.input :description, :wrapper => :prepend, :label => false do
    = content_tag :span, "Message", :class => "add-on"
    = f.input_field :description
  - $cnt = 0
  = f.simple_fields_for :events do |m|
    = if ($cnt == @count  )
      = m.input :message, :wrapper => :prepend, :label => false do
        = content_tag :span, "Event", :class => "add-on"
        = m.input_field :message
      = m.input :status_id, :collection =>  @statuses
    -$cnt += 1

  %br
  = f.button :submit, :class => 'btn-primary'

app/views/services/edit.html.haml
%div.page-header
  %h1 Editing service

= render 'form'

= link_to 'Show', @service
\|
-#= link_to 'Back', services_path

app/views/services/index.html.haml
%div.page-header
  %h1 Services
.container
  %table.table.table-bordered.table-striped.table-condensed
    %thead
      %tr
        %th Service
        %th Current
        -(1..6).each do |num|
          -#-date = Date.today-num
          -d = Time.now - (num * 86400)
          -date = d.utc
          %th= date.strftime('%b %d')
          -#%th= Date.today.('%m-%d')
        -if current_user
          %th
    %tbody
      - @services.each do |service|
        %tr
          %td= link_to service.name, service
          -(0..6).each do |num|
            %td

              - t = Time.now - (num * 86400)
              - time = t.utc
              - dateutc = time.strftime("%Y-%m-%d")
              -#%br= date = dateutc-num
              -maxevnt = {}
              -@evntdate = Event.joins('INNER JOIN services ON events.service_id = services.id INNER JOIN statuses ON events.status_id = statuses.id').where("events.service_id= ? AND events.created_at > ? ",service.id, time.to_date )
              -@evntdate.each do |e|
                -if(time.to_date ==  e.created_at.to_date)
                  -maxevnt[e.id] = e.created_at
              -max = maxevnt.max_by{|k,v| v}
              -unless max.nil?
                -eventid = max[0]
                -img = []
                -@evntdate.each do |e|
                  -@status.each do |st|
                    -if(e.id == eventid && st.id == e.status_id)
                      - img.push(st.images)
                %i{:class=>img.uniq[0]}
              -else
                %i{:class=>"icon-star-empty"}
          -if current_user
            %td
              %button.btn.btn-danger.btn-small
                %i.icon-remove-sign
                = link_to 'Delete', service, :confirm => 'Are you sure?', :method => :delete
  -if current_user
    %p
      %button.btn.btn-success
        = link_to 'New Service', new_service_path
  .container.span4
    %table.table.table-bordered.table-striped.table-condensed
      %thead
        %tr
          %th{:colspan => "2"} Status Legend
        - @statuses.each do |status|
          %tr
            %td
              %i{:class=>status.images}
            %td= status.description

-

app/views/services/new.html.haml
%div.page-header
  %h1 New service

= render 'form'

= link_to 'Back', services_path

app/views/services/show.html.haml
%div.page-header
  %h1 #{@service.name}
  %h3 #{@service.description}
.container
  %table.table.table-bordered.table-striped.table-condensed
    %thead
    %tr
      %th Message
      %th Status
      %th Date
      -@event.each do |e|
        %tr
          %td= e.message
          %td
            -@statuses.each do |s|
              -if(s.id == e.status_id)
                %i{:class=>s.images}
          %td= e.created_at
  -if current_user
    %p
      %button.btn.btn-success
        = link_to 'Edit Service', edit_service_path(@service)