config/routes.rb
Stashed::Application.routes.draw do
 get "log_in" => "sessions#new", :as => "log_in"
 get "log_out" => "sessions#destroy", :as => "log_out"

 root :to => "services#index"
 resources :users
 resources :sessions
 resources :events
 resources :statuses
 resources :services

  get "home/index"

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :ok }
    end
  end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.haml
= simple_form_for @status do |f|
  -if @status.errors.any?
    #error_explanation
      %h2= "#{pluralize(@status.errors.count, "error")} prohibited this status from being saved:"
      %ul
        - @status.errors.full_messages.each do |msg|
          %li= msg
  = f.input :name, :wrapper => :prepend, :label => false do
    = content_tag :span, "Name", :class => "add-on"
    = f.input_field :name
  = f.input :description, :wrapper => :prepend, :label => false do
    = content_tag :span, "Description", :class => "add-on"
    = f.input_field :description
  -icons = ["icon-refresh", "icon-star","icon-star-empty","icon-th-large","icon-ok","icon-signal","icon-trash","icon-time","icon-repeat","icon-lock","icon-flag","icon-ok-circle","icon-remove-circle","icon-arrow-up","icon-arrow-down","icon-plus","icon-minus","icon-asterisk","icon-exclamation-sign","icon-warning-sign"]
  =f.input :images, :collection => icons

  = f.button :submit, :class => 'btn-primary'

app/views/statuses/edit.html.haml
%div.page-header
  %h1 Edit Status

= render 'form'

= link_to 'Show', @status
\|
= link_to 'Back', statuses_path

app/views/statuses/index.html.haml
%div.page-header
  %h1 Status
.container
  %table.table.table-bordered.table-striped.table-condensed
    %thead
      %tr
        %th Status
        %th Description
        %th Icon
        %th
    %tbody
      -@statuses.each do |status|
        %tr
          %td= link_to status.name, status
          %td= status.description
          %td
            %i{:class=>status.images}
          %td
            %button.btn.btn-warning.btn-small
              %i.icon-edit
              = link_to 'Edit', edit_status_path(status)
          %td
            %button.btn.btn-danger.btn-small
              %i.icon-remove-sign
              = link_to 'Delete', status, :confirm => 'Are you sure?', :method => :delete
  %p
    %button.btn.btn-success
      = link_to 'New Status', new_status_path

app/views/statuses/new.html.haml
%h1 Create Status
= render 'form'

app/views/statuses/show.html.haml
%div.page-header
  %h1 Status

.container
  %table.table.table-bordered.table-striped.table-condensed
    %tr
      %td Name
      %td Description
      %td
    %tr
      %td #{@status.name}
      %td #{@status.description}
      %td
        %i{:class=>@status.images}
  %button.btn.btn-success
    = link_to 'Edit Status', edit_status_path(@status)