config/routes.rb
Stashed::Application.routes.draw do
 get "log_in" => "sessions#new", :as => "log_in"
 get "log_out" => "sessions#destroy", :as => "log_out"

 root :to => "services#index"
 resources :users
 resources :sessions
 resources :events
 resources :statuses
 resources :services

  get "home/index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_one :status
  belongs_to :service

  accepts_nested_attributes_for :status
  #validates_presence_of :

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    #@events = @service.events
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    #@event = @service.events.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
    #@event = @service.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    #@event = @service.events.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
   # @event = @service.events.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  -if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :message
    = f.text_field :message
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%div.page-header
  %h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%div.page-header
  %h1 Events
.container
  %table.table.table-bordered.table-striped.table-condensed
    %thead
    %tr
      %th Event
      %th Time Created
      %th Time Updated
      %th Service
      %th Status
    - @events.each do |event|
      %tr
        %td= link_to event.message,event
        %td= event.created_at
        %td= event.updated_at
        %td= event.service_id
        %td= event.status_id

-#= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Message:
  = @event.message

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path